set(_AMENT_PACKAGE_NAME "fanuc_eth_ip")
set(fanuc_eth_ip_VERSION "0.0.0")
set(fanuc_eth_ip_MAINTAINER "user <paolo.franceschi@supsi.ch>")
set(fanuc_eth_ip_BUILD_DEPENDS "rclcpp" "rclpy")
set(fanuc_eth_ip_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_python")
set(fanuc_eth_ip_BUILD_EXPORT_DEPENDS "rclcpp" "rclpy")
set(fanuc_eth_ip_BUILDTOOL_EXPORT_DEPENDS )
set(fanuc_eth_ip_EXEC_DEPENDS "rclcpp" "rclpy")
set(fanuc_eth_ip_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(fanuc_eth_ip_GROUP_DEPENDS )
set(fanuc_eth_ip_MEMBER_OF_GROUPS )
set(fanuc_eth_ip_DEPRECATED "")
set(fanuc_eth_ip_EXPORT_TAGS)
list(APPEND fanuc_eth_ip_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
